; SDL

(include "preset_early.inc")
(include "preset_mid.inc")
(include "preset_late.inc")

(include "preset_user_early.inc")  ; GOH campaign presets
(include "preset_user_mid.inc")    ; GOH campaign presets
(include "preset_user_late.inc")   ; GOH campaign presets

(include "preset_test_early.inc")  ; test mode
(include "preset_test_mid.inc")    ; test mode
(include "preset_test_late.inc")   ; test mode
