export const guideSource = {
  title: "Все текущие доктрины в версии 1.059.0 + DLC",
  url: "https://steamcommunity.com/sharedfiles/filedetails?id=3555185261",
  period: "1939-1941",
};

export const commonDoctrine = "Все доктрины";

export const doctrineOptionsBySide = {
  germany: [commonDoctrine, "Универсальная", "Оборонительная", "Нестандартная", "Наступательная", "Поддержка"],
  ussr: [commonDoctrine, "Универсальная", "Оборонительная", "Нестандартная", "Наступательная", "Поддержка"],
};

export const unitCategories = [
  "Пехота",
  "Пехота доктрины",
  "Инженеры",
  "ПТО",
  "Артиллерия",
  "Транспорт",
  "Броня",
  "Авиация",
  "Снабжение",
  "Командование",
  "Другое",
];

const g = "germany";
const s = "ussr";
const all = commonDoctrine;

const doctrinePointUnitIds = new Set([
  "g-d-engineer-squad", "g-d-sdkfz104", "g-d-pak36", "g-d-nbw35", "g-d-flak37", "g-d-pak38", "g-d-flak18", "g-d-sfh18", "g-d-morser18",
  "g-n-bf109", "g-n-mountain-sniper", "g-n-sdkfz231", "g-n-brandenburgers", "g-n-lg40", "g-n-flak41", "g-n-bf110", "g-n-sig33",
  "g-o-kfz14", "g-o-panzer2f", "g-o-sdkfz251-2", "g-o-panzer-pioneers", "g-o-sdkfz62", "g-o-panzer3h", "g-o-panzer4f1", "g-o-sturmpanzer1", "g-o-sdkfz8-flak",
  "g-s-supply-officer", "g-s-sdkfz221x2", "g-s-flak38", "g-s-recon-plane", "g-s-supply-convoy", "g-s-stug3b", "g-s-k18", "g-s-karl",
  "s-u-mg-teams-x2", "s-u-ba10", "s-u-bt7a", "s-u-t28-1938", "s-u-spotter", "s-u-122-1910", "s-u-t34-1940", "s-u-kv1-1940", "s-u-122-a19",
  "s-d-rifle-shields", "s-d-motorized", "s-d-45-1938", "s-d-120-pm38", "s-d-37-61k", "s-d-57-zis2", "s-d-85-52k", "s-d-152-ml20", "s-d-203-b4",
  "s-n-yak1", "s-n-ampulomet", "s-n-xt26", "s-n-bpk76", "s-n-recon", "s-n-f22", "s-n-il2", "s-n-107-1910", "s-n-smk",
  "s-o-ba20-command", "s-o-t30-1940", "s-o-t26-1938", "s-o-76-1902", "s-o-t28e", "s-o-t35-1938", "s-o-yag10-29k", "s-o-kv1-1939", "s-o-kv2-1940",
  "s-s-politruk", "s-s-bt5", "s-s-su26", "s-s-recon-plane", "s-s-supply-convoy", "s-s-76-1938", "s-s-t34x2", "s-s-152-br2", "s-s-280-br5",
]);

const guideUnitCatalogRaw = [
  { id: "g-inf-rifleman", side: g, doctrine: all, category: "Пехота", name: "Стрелок", cost: 10, command: 2 },
  { id: "g-inf-smg", side: g, doctrine: all, category: "Пехота", name: "Автоматчик", cost: 13, command: 3 },
  { id: "g-inf-mg", side: g, doctrine: all, category: "Пехота", name: "Пулемётчик", cost: 43, command: 6 },
  { id: "g-inf-at-rifle", side: g, doctrine: all, category: "ПТО", name: "Противотанковый расчёт", cost: 38, command: 6 },
  { id: "g-inf-rifle-grenade", side: g, doctrine: all, category: "Пехота", name: "Винтовочный гранатомётчик", cost: 26, command: 6 },
  { id: "g-inf-ap-miner", side: g, doctrine: all, category: "Инженеры", name: "Минёр противопехотный", cost: 80, command: 6 },
  { id: "g-inf-at-miner", side: g, doctrine: all, category: "Инженеры", name: "Минёр противотанковый", cost: 80, command: 6 },
  { id: "g-inf-engineer", side: g, doctrine: all, category: "Инженеры", name: "Войсковой инженер", cost: 100, command: 6 },
  { id: "g-inf-flamer", side: g, doctrine: all, category: "Инженеры", name: "Огнемётчик", cost: 45, command: 3 },
  { id: "g-inf-tanker", side: g, doctrine: all, category: "Пехота", name: "Танкист", cost: 26, command: 10 },
  { id: "g-inf-medic", side: g, doctrine: all, category: "Пехота", name: "Санитар", cost: 40, command: 3 },
  { id: "g-inf-sniper", side: g, doctrine: all, category: "Пехота", name: "Снайпер", cost: 150, command: 8 },
  { id: "g-inf-officer", side: g, doctrine: all, category: "Командование", name: "Офицер", cost: 125, command: 3 },
  { id: "g-supply-ammo-box", side: g, doctrine: all, category: "Снабжение", name: "Ящик с боеприпасами", cost: 66, command: 4 },
  { id: "g-gun-mg34", side: g, doctrine: all, category: "Пехота", name: "Станковый MG 34", cost: 100, command: 6 },
  { id: "g-gun-flak30", side: g, doctrine: all, category: "ПТО", name: "2-см FlaK 30", cost: 200, command: 12 },
  { id: "g-gun-spzb41", side: g, doctrine: all, category: "ПТО", name: "2,8-см sPzB 41", cost: 170, command: 12 },
  { id: "g-gun-pak36", side: g, doctrine: all, category: "ПТО", name: "3,7-см PaK 36", cost: 200, command: 14 },
  { id: "g-gun-pakt", side: g, doctrine: all, category: "ПТО", name: "4,7-см PaK(t)", cost: 270, command: 14 },
  { id: "g-gun-leig18", side: g, doctrine: all, category: "Артиллерия", name: "7,5-см leIG 18", cost: 360, command: 20 },
  { id: "g-gun-sgrw34", side: g, doctrine: all, category: "Артиллерия", name: "8-см sGrW 34", cost: 260, command: 16 },
  { id: "g-gun-lefh18", side: g, doctrine: all, category: "Артиллерия", name: "10,5-см LeFH 18", cost: 770, command: 34 },
  { id: "g-veh-r71", side: g, doctrine: all, category: "Транспорт", name: "BMW R71 (MG34)", cost: 60, command: 7 },
  { id: "g-veh-kz15", side: g, doctrine: all, category: "Транспорт", name: "Kfz.15 (MG34)", cost: 75, command: 8 },
  { id: "g-veh-sdkfz2", side: g, doctrine: all, category: "Транспорт", name: "Sd.Kfz 2", cost: 15, command: 4 },
  { id: "g-veh-kfz70", side: g, doctrine: all, category: "Транспорт", name: "Kfz.70 (транспорт)", cost: 25, command: 4 },
  { id: "g-veh-opel-transport", side: g, doctrine: all, category: "Транспорт", name: "Opel Blitz (транспорт)", cost: 30, command: 4 },
  { id: "g-veh-sdkfz10", side: g, doctrine: all, category: "Транспорт", name: "Sd.Kfz 10", cost: 30, command: 4 },
  { id: "g-veh-sdkfz7", side: g, doctrine: all, category: "Транспорт", name: "Sd.Kfz 7 (транспорт)", cost: 30, command: 4 },
  { id: "g-veh-sdkfz251c", side: g, doctrine: all, category: "Транспорт", name: "Sd.Kfz 251/1 Ausf.C", cost: 110, command: 8 },
  { id: "g-veh-kfz13", side: g, doctrine: all, category: "Транспорт", name: "Kfz.13 (MG34)", cost: 125, command: 8 },
  { id: "g-veh-opel-20mm", side: g, doctrine: all, category: "ПТО", name: "Opel Blitz (2-см)", cost: 245, command: 16 },
  { id: "g-veh-sdkfz222", side: g, doctrine: all, category: "Транспорт", name: "Sd.Kfz 222 Ausf.A", cost: 260, command: 14 },
  { id: "g-veh-opel-supply", side: g, doctrine: all, category: "Снабжение", name: "Opel Blitz (грузовой)", cost: 200, command: 8 },
  { id: "g-veh-opel-fuel", side: g, doctrine: all, category: "Снабжение", name: "Opel Blitz (топливо)", cost: 100, command: 4 },
  { id: "g-veh-opel-engineer", side: g, doctrine: all, category: "Инженеры", name: "Opel Blitz (инженерный)", cost: 180, command: 8 },
  { id: "g-tank-pz1b", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw I Ausf.B", cost: 130, command: 12 },
  { id: "g-tank-pz2c", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw II Ausf.C", cost: 240, command: 18 },
  { id: "g-tank-pz2f", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw II Ausf.F", cost: 285, command: 18 },
  { id: "g-tank-pz35t", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw 35(t)", cost: 265, command: 20 },
  { id: "g-tank-pz38a", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw 38(t) Ausf.A", cost: 275, command: 20 },
  { id: "g-tank-pz3e", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw III Ausf.E", cost: 340, command: 25 },
  { id: "g-tank-pz3f", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw III Ausf.F", cost: 370, command: 25 },
  { id: "g-tank-pz4d", side: g, doctrine: all, category: "Броня", name: "Pz.Kpfw IV Ausf.D", cost: 400, command: 25 },
  { id: "g-tank-panzerjager1", side: g, doctrine: all, category: "ПТО", name: "Panzerjäger I", cost: 300, command: 18 },

  { id: "g-u-riflemen-ersatz", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Стрелки Эрзац", cost: 70, command: 20 },
  { id: "g-u-scouts", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Разведчики", cost: 75, command: 15 },
  { id: "g-u-riflemen", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Стрелки", cost: 113, command: 29 },
  { id: "g-u-at-riflemen", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Противотанковые стрелки", cost: 124, command: 21 },
  { id: "g-u-veterans", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Стрелки-ветераны", cost: 155, command: 36 },
  { id: "g-u-elite", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Элитные стрелки", cost: 233, command: 36 },
  { id: "g-u-mountain-scouts", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Горные разведчики", cost: 183, command: 24 },
  { id: "g-u-mountain-jaegers", side: g, doctrine: "Универсальная", category: "Пехота доктрины", name: "Горные егеря", cost: 224, command: 30 },
  { id: "g-d-engineer-squad", side: g, doctrine: "Оборонительная", category: "Инженеры", name: "Отряд сапёров", cost: 5, command: 14 },
  { id: "g-d-sdkfz104", side: g, doctrine: "Оборонительная", category: "ПТО", name: "Sd.Kfz 10/4 (2-см)", cost: 15, command: 16 },
  { id: "g-d-pak36", side: g, doctrine: "Оборонительная", category: "ПТО", name: "3,7-см PaK 36", cost: 20, command: 18 },
  { id: "g-d-nbw35", side: g, doctrine: "Оборонительная", category: "Артиллерия", name: "10-см NbW 35", cost: 25, command: 18 },
  { id: "g-d-flak37", side: g, doctrine: "Оборонительная", category: "ПТО", name: "3,7-см FlaK 37", cost: 30, command: 20 },
  { id: "g-d-pak38", side: g, doctrine: "Оборонительная", category: "ПТО", name: "5-см PaK 38", cost: 40, command: 24 },
  { id: "g-d-flak18", side: g, doctrine: "Оборонительная", category: "ПТО", name: "8,8-см FlaK 18", cost: 80, command: 34 },
  { id: "g-d-sfh18", side: g, doctrine: "Оборонительная", category: "Артиллерия", name: "15-см sFH 18", cost: 75, command: 44 },
  { id: "g-d-morser18", side: g, doctrine: "Оборонительная", category: "Артиллерия", name: "21-см Mörser 18", cost: 85, command: 46 },
  { id: "g-d-landwehr", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Стрелки Ландвер", cost: 88, command: 20 },
  { id: "g-d-scouts", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Разведчики", cost: 75, command: 15 },
  { id: "g-d-field-police-1", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Полевая жандармерия 1", cost: 50, command: 13 },
  { id: "g-d-field-police-2", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Полевая жандармерия 2", cost: 52, command: 14 },
  { id: "g-d-field-police-3", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Полевая жандармерия 3", cost: 77, command: 14 },
  { id: "g-d-at-riflemen", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Противотанковые стрелки", cost: 124, command: 21 },
  { id: "g-d-pioneers", side: g, doctrine: "Оборонительная", category: "Инженеры", name: "Пионеры", cost: 162, command: 36 },
  { id: "g-d-grossdeutschland", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Стрелки Великая Германия", cost: 201, command: 30 },
  { id: "g-d-mountain-jaegers", side: g, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Горные егеря", cost: 224, command: 30 },
  { id: "g-n-bf109", side: g, doctrine: "Нестандартная", category: "Авиация", name: "Bf-109 50кг бомба", cost: 10, command: 0 },
  { id: "g-n-mountain-sniper", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Горный снайпер", cost: 10, command: 8 },
  { id: "g-n-sdkfz231", side: g, doctrine: "Нестандартная", category: "Транспорт", name: "Sd.Kfz 231", cost: 15, command: 16 },
  { id: "g-n-brandenburgers", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Бранденбуржцы", cost: 20, command: 30 },
  { id: "g-n-lg40", side: g, doctrine: "Нестандартная", category: "Артиллерия", name: "7,5-см LG 40", cost: 30, command: 20 },
  { id: "g-n-flak41", side: g, doctrine: "Нестандартная", category: "ПТО", name: "5-см FlaK 41", cost: 50, command: 26 },
  { id: "g-n-bf110", side: g, doctrine: "Нестандартная", category: "Авиация", name: "Bf-110 250кг бомба", cost: 30, command: 0 },
  { id: "g-n-sig33", side: g, doctrine: "Нестандартная", category: "Артиллерия", name: "15-см sIG 33", cost: 60, command: 32 },
  { id: "g-n-ersatz", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Стрелки Эрзац", cost: 70, command: 20 },
  { id: "g-n-luftwaffe", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Стрелки Люфтваффе", cost: 97, command: 25 },
  { id: "g-n-riflemen", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Стрелки", cost: 118, command: 23 },
  { id: "g-n-at-riflemen", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Противотанковые стрелки", cost: 124, command: 21 },
  { id: "g-n-veterans", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Стрелки-ветераны", cost: 155, command: 36 },
  { id: "g-n-marines", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Морпехи-штурмовики", cost: 143, command: 27 },
  { id: "g-n-fallschirm-scouts", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Парашютисты-разведчики", cost: 190, command: 24 },
  { id: "g-n-fallschirm-pioneers", side: g, doctrine: "Нестандартная", category: "Инженеры", name: "Парашютисты-пионеры", cost: 262, command: 36 },
  { id: "g-n-fallschirm", side: g, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Парашютисты", cost: 264, command: 36 },
  { id: "g-o-kfz14", side: g, doctrine: "Наступательная", category: "Командование", name: "Kfz.14 Командирский", cost: 5, command: 11 },
  { id: "g-o-panzer2f", side: g, doctrine: "Наступательная", category: "Броня", name: "Panzer II Ausf.F", cost: 20, command: 18 },
  { id: "g-o-sdkfz251-2", side: g, doctrine: "Наступательная", category: "Артиллерия", name: "Sd.Kfz 251/2 (8-см)", cost: 25, command: 20 },
  { id: "g-o-panzer-pioneers", side: g, doctrine: "Наступательная", category: "Инженеры", name: "Панцерпионеры", cost: 30, command: 56 },
  { id: "g-o-sdkfz62", side: g, doctrine: "Наступательная", category: "ПТО", name: "Sd.Kfz 6/2 (3,7-см)", cost: 30, command: 20 },
  { id: "g-o-panzer3h", side: g, doctrine: "Наступательная", category: "Броня", name: "Panzer III Ausf.H", cost: 45, command: 25 },
  { id: "g-o-panzer4f1", side: g, doctrine: "Наступательная", category: "Броня", name: "Panzer IV Ausf.F1", cost: 50, command: 25 },
  { id: "g-o-sturmpanzer1", side: g, doctrine: "Наступательная", category: "Броня", name: "Sturmpanzer I", cost: 60, command: 24 },
  { id: "g-o-sdkfz8-flak", side: g, doctrine: "Наступательная", category: "ПТО", name: "Sd.Kfz 8 (8,8-см)", cost: 80, command: 28 },
  { id: "g-o-armored-scouts", side: g, doctrine: "Наступательная", category: "Пехота доктрины", name: "Бронетанковые разведчики", cost: 119, command: 21 },
  { id: "g-o-motorized", side: g, doctrine: "Наступательная", category: "Пехота доктрины", name: "Мотопехота", cost: 150, command: 31 },
  { id: "g-o-panzergrenadiers", side: g, doctrine: "Наступательная", category: "Пехота доктрины", name: "Панзергренадёры", cost: 182, command: 36 },
  { id: "g-o-grossdeutschland", side: g, doctrine: "Наступательная", category: "Пехота доктрины", name: "Стрелки Великая Германия", cost: 201, command: 30 },
  { id: "g-o-pioneers-grossdeutschland", side: g, doctrine: "Наступательная", category: "Инженеры", name: "Пионеры Великая Германия", cost: 262, command: 36 },
  { id: "g-o-mountain-jaegers", side: g, doctrine: "Наступательная", category: "Пехота доктрины", name: "Горные егеря", cost: 224, command: 30 },
  { id: "g-s-supply-officer", side: g, doctrine: "Поддержка", category: "Командование", name: "Офицер снабжения", cost: 10, command: 3 },
  { id: "g-s-sdkfz221x2", side: g, doctrine: "Поддержка", category: "Транспорт", name: "2x Sd.Kfz 221", cost: 15, command: 16 },
  { id: "g-s-flak38", side: g, doctrine: "Поддержка", category: "ПТО", name: "2cm Flak 38", cost: 15, command: 16 },
  { id: "g-s-recon-plane", side: g, doctrine: "Поддержка", category: "Авиация", name: "Самолёт-разведчик", cost: 5, command: 0 },
  { id: "g-s-supply-convoy", side: g, doctrine: "Поддержка", category: "Снабжение", name: "Конвой снабжения", cost: 40, command: 16 },
  { id: "g-s-stug3b", side: g, doctrine: "Поддержка", category: "Броня", name: "StuG III Ausf.B", cost: 45, command: 24 },
  { id: "g-s-k18", side: g, doctrine: "Поддержка", category: "Артиллерия", name: "17-см K18", cost: 105, command: 46 },
  { id: "g-s-karl", side: g, doctrine: "Поддержка", category: "Артиллерия", name: "60-см Karl Gerät", cost: 105, command: 60 },
  { id: "g-s-ersatz", side: g, doctrine: "Поддержка", category: "Пехота доктрины", name: "Стрелки Эрзац", cost: 70, command: 20 },
  { id: "g-s-kriegsmarine", side: g, doctrine: "Поддержка", category: "Пехота доктрины", name: "Стрелки Кригсмарине", cost: 107, command: 25 },
  { id: "g-s-at-riflemen", side: g, doctrine: "Поддержка", category: "Пехота доктрины", name: "Противотанковые стрелки", cost: 124, command: 21 },
  { id: "g-s-veterans", side: g, doctrine: "Поддержка", category: "Пехота доктрины", name: "Стрелки-ветераны", cost: 155, command: 36 },
  { id: "g-s-marines", side: g, doctrine: "Поддержка", category: "Пехота доктрины", name: "Морпехи-штурмовики", cost: 143, command: 27 },
  { id: "g-s-mountain-scouts", side: g, doctrine: "Поддержка", category: "Пехота доктрины", name: "Горные разведчики", cost: 183, command: 24 },
  { id: "g-s-mountain-jaegers", side: g, doctrine: "Поддержка", category: "Пехота доктрины", name: "Горные егеря", cost: 224, command: 30 },
  { id: "g-s-mountain-pioneers", side: g, doctrine: "Поддержка", category: "Инженеры", name: "Горные пионеры", cost: 260, command: 36 },

  { id: "s-inf-rifleman", side: s, doctrine: all, category: "Пехота", name: "Стрелок", cost: 10, command: 2 },
  { id: "s-inf-semi-auto", side: s, doctrine: all, category: "Пехота", name: "Стрелок с полуавт. винтовкой", cost: 17, command: 3 },
  { id: "s-inf-assault-rifle-team", side: s, doctrine: all, category: "Пехота", name: "Звено штурм. винтовки", cost: 38, command: 6 },
  { id: "s-inf-mg-team", side: s, doctrine: all, category: "Пехота", name: "Пулемётный расчёт", cost: 43, command: 6 },
  { id: "s-inf-at-rifle", side: s, doctrine: all, category: "ПТО", name: "Противотанковый расчёт", cost: 21, command: 6 },
  { id: "s-inf-rifle-grenade", side: s, doctrine: all, category: "Пехота", name: "Винтовочный гранатомётчик", cost: 13, command: 3 },
  { id: "s-inf-ap-miner", side: s, doctrine: all, category: "Инженеры", name: "Минёр противопехотный", cost: 80, command: 6 },
  { id: "s-inf-at-miner", side: s, doctrine: all, category: "Инженеры", name: "Минёр противотанковый", cost: 80, command: 6 },
  { id: "s-inf-engineer", side: s, doctrine: all, category: "Инженеры", name: "Войсковой инженер", cost: 100, command: 6 },
  { id: "s-inf-flamer", side: s, doctrine: all, category: "Инженеры", name: "Огнемётчик", cost: 60, command: 3 },
  { id: "s-inf-tanker", side: s, doctrine: all, category: "Пехота", name: "Танкист", cost: 26, command: 10 },
  { id: "s-inf-medic", side: s, doctrine: all, category: "Пехота", name: "Санитар", cost: 40, command: 3 },
  { id: "s-inf-sniper", side: s, doctrine: all, category: "Пехота", name: "Снайпер", cost: 150, command: 8 },
  { id: "s-inf-commissar", side: s, doctrine: all, category: "Командование", name: "Комиссар", cost: 125, command: 3 },
  { id: "s-supply-ammo-box", side: s, doctrine: all, category: "Снабжение", name: "Советский ящик с боеприпасами", cost: 66, command: 4 },
  { id: "s-gun-maxim", side: s, doctrine: all, category: "Пехота", name: "Максим обр. 1910/30 г.", cost: 100, command: 6 },
  { id: "s-gun-dshk-stan", side: s, doctrine: all, category: "Пехота", name: "ДШК обр. 1938 г. станковый", cost: 150, command: 10 },
  { id: "s-gun-dshk", side: s, doctrine: all, category: "Пехота", name: "ДШК обр. 1938 г.", cost: 150, command: 10 },
  { id: "s-gun-37-1k", side: s, doctrine: all, category: "ПТО", name: "37-мм 1-К обр. 1930 г.", cost: 160, command: 14 },
  { id: "s-gun-45-m37", side: s, doctrine: all, category: "ПТО", name: "45-мм М-37 обр. 1937 г.", cost: 200, command: 14 },
  { id: "s-gun-76-1933", side: s, doctrine: all, category: "Артиллерия", name: "76-мм обр. 1933 г.", cost: 360, command: 20 },
  { id: "s-gun-76-1927", side: s, doctrine: all, category: "Артиллерия", name: "76-мм обр. 1927 г.", cost: 360, command: 20 },
  { id: "s-gun-82-bm37", side: s, doctrine: all, category: "Артиллерия", name: "82-мм БМ-37 обр. 1937 г.", cost: 260, command: 16 },
  { id: "s-gun-122-m30", side: s, doctrine: all, category: "Артиллерия", name: "122-мм М-30 обр. 1938 г.", cost: 800, command: 34 },
  { id: "s-veh-m72-dp27", side: s, doctrine: all, category: "Транспорт", name: "M72 (ДП-27)", cost: 60, command: 6 },
  { id: "s-veh-zis5", side: s, doctrine: all, category: "Транспорт", name: "ЗиС-5", cost: 30, command: 4 },
  { id: "s-veh-gaz-aaa-transport", side: s, doctrine: all, category: "Транспорт", name: "ГАЗ-ААА (транспортный)", cost: 30, command: 4 },
  { id: "s-veh-t27", side: s, doctrine: all, category: "Броня", name: "Т-27", cost: 95, command: 8 },
  { id: "s-veh-fai-m", side: s, doctrine: all, category: "Транспорт", name: "ФАИ-М", cost: 125, command: 10 },
  { id: "s-veh-ba6", side: s, doctrine: all, category: "Транспорт", name: "БА-6", cost: 240, command: 16 },
  { id: "s-veh-gaz-aaa-m4", side: s, doctrine: all, category: "ПТО", name: "ГАЗ-ААА (М4 ЗПУ)", cost: 125, command: 12 },
  { id: "s-veh-zis5-dshk", side: s, doctrine: all, category: "ПТО", name: "ЗиС-5 (ДШК)", cost: 165, command: 14 },
  { id: "s-veh-gaz-aaa-supply", side: s, doctrine: all, category: "Снабжение", name: "ГАЗ-ААА (снабжение)", cost: 200, command: 8 },
  { id: "s-veh-gaz-aaa-fuel", side: s, doctrine: all, category: "Снабжение", name: "ГАЗ-ААА (топливо)", cost: 100, command: 4 },
  { id: "s-veh-zis5-engineer", side: s, doctrine: all, category: "Инженеры", name: "ЗиС-5 (инженерный)", cost: 180, command: 8 },
  { id: "s-tank-t26-1931", side: s, doctrine: all, category: "Броня", name: "Т-26 обр. 1931 г.", cost: 130, command: 14 },
  { id: "s-tank-t40-1940", side: s, doctrine: all, category: "Броня", name: "Т-40 обр. 1940 г.", cost: 185, command: 16 },
  { id: "s-tank-t26-1933", side: s, doctrine: all, category: "Броня", name: "Т-26 обр. 1933 г.", cost: 245, command: 18 },
  { id: "s-tank-bt2-da2", side: s, doctrine: all, category: "Броня", name: "БТ-2 ДА-2", cost: 180, command: 16 },
  { id: "s-tank-bt2", side: s, doctrine: all, category: "Броня", name: "БТ-2", cost: 245, command: 18 },
  { id: "s-tank-bt7-1937", side: s, doctrine: all, category: "Броня", name: "БТ-7 обр. 1937 г.", cost: 295, command: 18 },
  { id: "s-tank-t28-1936", side: s, doctrine: all, category: "Броня", name: "Т-28 обр. 1936 г.", cost: 375, command: 27 },
  { id: "s-tank-t35-1936", side: s, doctrine: all, category: "Броня", name: "Т-35 обр. 1936 г.", cost: 410, command: 40 },

  { id: "s-u-mg-teams-x2", side: s, doctrine: "Универсальная", category: "Пехота", name: "2x пулемётных расчёта", cost: 15, command: 20 },
  { id: "s-u-ba10", side: s, doctrine: "Универсальная", category: "Транспорт", name: "БА-10", cost: 15, command: 16 },
  { id: "s-u-bt7a", side: s, doctrine: "Универсальная", category: "Броня", name: "БТ-7А", cost: 25, command: 18 },
  { id: "s-u-t28-1938", side: s, doctrine: "Универсальная", category: "Броня", name: "Т-28 обр. 1938 г.", cost: 35, command: 27 },
  { id: "s-u-spotter", side: s, doctrine: "Универсальная", category: "Командование", name: "Корректировщик", cost: 60, command: 3 },
  { id: "s-u-122-1910", side: s, doctrine: "Универсальная", category: "Артиллерия", name: "122-мм обр. 1910 г.", cost: 70, command: 38 },
  { id: "s-u-t34-1940", side: s, doctrine: "Универсальная", category: "Броня", name: "Т-34 обр. 1940 г.", cost: 60, command: 41 },
  { id: "s-u-kv1-1940", side: s, doctrine: "Универсальная", category: "Броня", name: "КВ-1 обр. 1940 г.", cost: 90, command: 36 },
  { id: "s-u-122-a19", side: s, doctrine: "Универсальная", category: "Артиллерия", name: "122-мм A-19", cost: 90, command: 40 },
  { id: "s-u-border-guards", side: s, doctrine: "Универсальная", category: "Пехота доктрины", name: "Пограничники", cost: 77, command: 22 },
  { id: "s-u-scouts", side: s, doctrine: "Универсальная", category: "Пехота доктрины", name: "Разведчики", cost: 107, command: 23 },
  { id: "s-u-riflemen", side: s, doctrine: "Универсальная", category: "Пехота доктрины", name: "Стрелки", cost: 115, command: 25 },
  { id: "s-u-cavalry-sappers", side: s, doctrine: "Универсальная", category: "Инженеры", name: "Кавалерийские сапёры", cost: 167, command: 30 },
  { id: "s-u-cavalry-riflemen", side: s, doctrine: "Универсальная", category: "Пехота доктрины", name: "Кавалерийские стрелки", cost: 180, command: 33 },
  { id: "s-u-paratroopers", side: s, doctrine: "Универсальная", category: "Пехота доктрины", name: "Десантники", cost: 270, command: 36 },
  { id: "s-d-rifle-shields", side: s, doctrine: "Оборонительная", category: "Другое", name: "6x ружейных щитов", cost: 5, command: 12 },
  { id: "s-d-motorized", side: s, doctrine: "Оборонительная", category: "Транспорт", name: "Моторизованные части", cost: 15, command: 32 },
  { id: "s-d-45-1938", side: s, doctrine: "Оборонительная", category: "ПТО", name: "45-мм обр. 1938 г.", cost: 20, command: 18 },
  { id: "s-d-120-pm38", side: s, doctrine: "Оборонительная", category: "Артиллерия", name: "120-мм ПМ-38", cost: 30, command: 24 },
  { id: "s-d-37-61k", side: s, doctrine: "Оборонительная", category: "ПТО", name: "37-мм 61-К обр. 1939 г.", cost: 30, command: 19 },
  { id: "s-d-57-zis2", side: s, doctrine: "Оборонительная", category: "ПТО", name: "57-мм ЗиС-2", cost: 60, command: 32 },
  { id: "s-d-85-52k", side: s, doctrine: "Оборонительная", category: "ПТО", name: "85-мм 52-К", cost: 65, command: 32 },
  { id: "s-d-152-ml20", side: s, doctrine: "Оборонительная", category: "Артиллерия", name: "152-мм МЛ-20", cost: 85, command: 44 },
  { id: "s-d-203-b4", side: s, doctrine: "Оборонительная", category: "Артиллерия", name: "203-мм Б-4", cost: 85, command: 44 },
  { id: "s-d-border-guards", side: s, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Пограничники", cost: 77, command: 22 },
  { id: "s-d-scouts", side: s, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Разведчики", cost: 107, command: 23 },
  { id: "s-d-sappers", side: s, doctrine: "Оборонительная", category: "Инженеры", name: "Сапёры", cost: 65, command: 18 },
  { id: "s-d-riflemen", side: s, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Стрелки", cost: 115, command: 25 },
  { id: "s-d-mountain-sappers", side: s, doctrine: "Оборонительная", category: "Инженеры", name: "Горные сапёры", cost: 139, command: 27 },
  { id: "s-d-mountain-riflemen", side: s, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Горные стрелки", cost: 198, command: 36 },
  { id: "s-d-glider", side: s, doctrine: "Оборонительная", category: "Пехота доктрины", name: "Планеристы", cost: 269, command: 36 },
  { id: "s-n-yak1", side: s, doctrine: "Нестандартная", category: "Авиация", name: "Як-1 50кг бомба", cost: 10, command: 0 },
  { id: "s-n-ampulomet", side: s, doctrine: "Нестандартная", category: "Артиллерия", name: "Ампуломёт обр. 1941 г.", cost: 10, command: 12 },
  { id: "s-n-xt26", side: s, doctrine: "Нестандартная", category: "Броня", name: "ХТ-26 (огнемёт)", cost: 10, command: 16 },
  { id: "s-n-bpk76", side: s, doctrine: "Нестандартная", category: "Артиллерия", name: "76-мм БПК-76", cost: 35, command: 24 },
  { id: "s-n-recon", side: s, doctrine: "Нестандартная", category: "Командование", name: "Разведка", cost: 15, command: 18 },
  { id: "s-n-f22", side: s, doctrine: "Нестандартная", category: "Артиллерия", name: "76-мм Ф-22", cost: 50, command: 28 },
  { id: "s-n-il2", side: s, doctrine: "Нестандартная", category: "Авиация", name: "ИЛ-2 250кг бомба", cost: 30, command: 0 },
  { id: "s-n-107-1910", side: s, doctrine: "Нестандартная", category: "Артиллерия", name: "107-мм обр. 1910 г.", cost: 75, command: 38 },
  { id: "s-n-smk", side: s, doctrine: "Нестандартная", category: "Броня", name: "СМК", cost: 75, command: 34 },
  { id: "s-n-border-guards", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Пограничники", cost: 77, command: 22 },
  { id: "s-n-riflemen", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Стрелки", cost: 94, command: 24 },
  { id: "s-n-heavy-riflemen-1", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Тяжёлые стрелки 1", cost: 133, command: 30 },
  { id: "s-n-heavy-riflemen-2", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Тяжёлые стрелки 2", cost: 138, command: 30 },
  { id: "s-n-mountain-scouts", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Горные разведчики", cost: 141, command: 24 },
  { id: "s-n-mountain-riflemen", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Горные стрелки", cost: 198, command: 36 },
  { id: "s-n-paratrooper-scouts", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Десантники-разведчики", cost: 197, command: 30 },
  { id: "s-n-paratroopers", side: s, doctrine: "Нестандартная", category: "Пехота доктрины", name: "Десантники", cost: 271, command: 36 },
  { id: "s-o-ba20-command", side: s, doctrine: "Наступательная", category: "Командование", name: "БА-20 Командирский", cost: 5, command: 11 },
  { id: "s-o-t30-1940", side: s, doctrine: "Наступательная", category: "Броня", name: "Т-30 обр. 1940 г.", cost: 15, command: 16 },
  { id: "s-o-t26-1938", side: s, doctrine: "Наступательная", category: "Броня", name: "Т-26 обр. 1938 г.", cost: 15, command: 18 },
  { id: "s-o-76-1902", side: s, doctrine: "Наступательная", category: "Артиллерия", name: "76-мм обр. 1902 г.", cost: 35, command: 28 },
  { id: "s-o-t28e", side: s, doctrine: "Наступательная", category: "Броня", name: "Т-28 Е", cost: 40, command: 27 },
  { id: "s-o-t35-1938", side: s, doctrine: "Наступательная", category: "Броня", name: "Т-35 обр. 1938 г.", cost: 45, command: 40 },
  { id: "s-o-yag10-29k", side: s, doctrine: "Наступательная", category: "ПТО", name: "ЯГ-10 29-К", cost: 60, command: 24 },
  { id: "s-o-kv1-1939", side: s, doctrine: "Наступательная", category: "Броня", name: "КВ-1 обр. 1939 г.", cost: 80, command: 36 },
  { id: "s-o-kv2-1940", side: s, doctrine: "Наступательная", category: "Броня", name: "КВ-2 обр. 1940 г.", cost: 100, command: 42 },
  { id: "s-o-border-guards", side: s, doctrine: "Наступательная", category: "Пехота доктрины", name: "Пограничники", cost: 77, command: 22 },
  { id: "s-o-scouts", side: s, doctrine: "Наступательная", category: "Пехота доктрины", name: "Разведчики", cost: 107, command: 23 },
  { id: "s-o-riflemen", side: s, doctrine: "Наступательная", category: "Пехота доктрины", name: "Стрелки", cost: 127, command: 27 },
  { id: "s-o-cavalry-sappers", side: s, doctrine: "Наступательная", category: "Инженеры", name: "Кавалерийские сапёры", cost: 149, command: 27 },
  { id: "s-o-cavalry-riflemen", side: s, doctrine: "Наступательная", category: "Пехота доктрины", name: "Кавалерийские стрелки", cost: 185, command: 33 },
  { id: "s-o-paratroopers", side: s, doctrine: "Наступательная", category: "Пехота доктрины", name: "Десантники", cost: 312, command: 36 },
  { id: "s-s-politruk", side: s, doctrine: "Поддержка", category: "Командование", name: "Политрук", cost: 10, command: 3 },
  { id: "s-s-bt5", side: s, doctrine: "Поддержка", category: "Броня", name: "БТ-5", cost: 25, command: 18 },
  { id: "s-s-su26", side: s, doctrine: "Поддержка", category: "Броня", name: "Су-26", cost: 30, command: 18 },
  { id: "s-s-recon-plane", side: s, doctrine: "Поддержка", category: "Авиация", name: "Самолёт-разведчик", cost: 5, command: 0 },
  { id: "s-s-supply-convoy", side: s, doctrine: "Поддержка", category: "Снабжение", name: "Конвой снабжения", cost: 30, command: 30 },
  { id: "s-s-76-1938", side: s, doctrine: "Поддержка", category: "Артиллерия", name: "76-мм обр. 1938 г.", cost: 60, command: 28 },
  { id: "s-s-t34x2", side: s, doctrine: "Поддержка", category: "Броня", name: "2x Т-34 обр. 1940 г.", cost: 90, command: 58 },
  { id: "s-s-152-br2", side: s, doctrine: "Поддержка", category: "Артиллерия", name: "152-мм Бр-2", cost: 105, command: 44 },
  { id: "s-s-280-br5", side: s, doctrine: "Поддержка", category: "Артиллерия", name: "280-мм Бр-5", cost: 115, command: 50 },
  { id: "s-s-border-guards", side: s, doctrine: "Поддержка", category: "Пехота доктрины", name: "Пограничники", cost: 77, command: 22 },
  { id: "s-s-cossack-scouts", side: s, doctrine: "Поддержка", category: "Пехота доктрины", name: "Казаки-разведчики", cost: 75, command: 18 },
  { id: "s-s-cossack-riflemen", side: s, doctrine: "Поддержка", category: "Пехота доктрины", name: "Казаки-стрелки", cost: 138, command: 28 },
  { id: "s-s-mountain-sappers", side: s, doctrine: "Поддержка", category: "Инженеры", name: "Горные сапёры", cost: 139, command: 27 },
  { id: "s-s-mountain-riflemen", side: s, doctrine: "Поддержка", category: "Пехота доктрины", name: "Горные стрелки", cost: 198, command: 36 },
  { id: "s-s-glider-scouts", side: s, doctrine: "Поддержка", category: "Пехота доктрины", name: "Разведчики-планеристы", cost: 197, command: 30 },
  { id: "s-s-glider", side: s, doctrine: "Поддержка", category: "Пехота доктрины", name: "Планеристы", cost: 311, command: 36 },
];

export const guideUnitCatalog = guideUnitCatalogRaw.map((unit) => ({
  resource: doctrinePointUnitIds.has(unit.id) ? "ОД" : "ЛС",
  ...unit,
}));

export function getDoctrineOptions(side) {
  return doctrineOptionsBySide[side] || doctrineOptionsBySide.germany;
}

export function getCatalogUnits(side, doctrine) {
  return guideUnitCatalog
    .filter((unit) => unit.side === side && (unit.doctrine === commonDoctrine || unit.doctrine === doctrine))
    .sort((a, b) => {
      if (a.doctrine !== b.doctrine) return a.doctrine === commonDoctrine ? -1 : 1;
      if (a.category !== b.category) return unitCategories.indexOf(a.category) - unitCategories.indexOf(b.category);
      return a.cost - b.cost || a.name.localeCompare(b.name, "ru");
    });
}
